name: Docker

on:
  push:
    branches:
      - develop
      - 1.0-develop
  pull_request:
    branches:
      - develop
      - 1.0-develop
  release:
    types:
      - published

jobs:
  push:
    name: Push
    runs-on: ubuntu-20.04
    if: "!contains(github.ref, 'develop') || (!contains(github.event.head_commit.message, 'skip docker') && !contains(github.event.head_commit.message, 'docker skip'))"
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/pterodactyl-china/panel
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'release' && github.event.action == 'published' && github.event.release.prerelease == false }}
            type=ref,event=tag
            type=ref,event=branch

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Update version
        if: "github.event_name == 'release' && github.event.action == 'published'"
        env:
          REF: ${{ github.event.release.tag_name }}
        run: |
          sed -i "s/    'version' => 'canary',/    'version' => '${REF:1}',/" config/app.php

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64 #,linux/arm64
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
